exports.artists = [
    {name: "J. Cole",
    born: new Date(1985, 0, 28),
    hometown: "Fayetville, NC"},
    {name: "Justin Bieber",
    born:new Date(1994, 02, 01),
    hometown: "London, ON"},
    {name: "Thomas Rhett",
    born:new Date(1990, 02, 30),
    hometown: "Valdosta, GA"},
    {name: "Caribou",
    born:new Date(1978),
    hometown: "Dundas, ON"},
    {name: "Drake",
    born:new Date(1986, 09, 24),
    hometown: "Toronto, ON"},
    {name: "Taylor Swift",
    born:new Date(1989, 11, 13),
    hometown: "Reading, PA"},
    {name: "Kane Brown",
    born:new Date(1993, 09, 21),
    hometown: "Chattanooga, TN"},
    {name: "Maroon 5",
    hometown:"Los Angeles, CA"},
    {name: "Imagine Dragons",
    hometown: "Las Vegas, NV"}    
]